export { default as iconBee } from './🐝.png';
export { default as iconDesign } from './🎨.png';
export { default as iconDev } from './💻.png';
export { default as iconCopywriting } from './✍️.png';
export { default as iconMarketing } from './📈.png';
export { default as iconVideo } from './🎬.png';
export { default as iconAudio } from './🎵.png';
export { default as iconBusiness } from './📊.png';
export { default as iconPhoto } from './📷.png';
export { default as iconProgramming } from './⚙️.png';
export { default as iconArch } from './🏗️.png';
export { default as iconEngineering } from './🔧.png';
export { default as iconEducation } from './📚.png';
export { default as iconCheck } from './✅.png';
export { default as iconMoney } from './💰.png';
export { default as iconLightning } from './⚡.png';
export { default as iconShield } from './🛡️.png';
export { default as iconChat } from './💬.png';
export { default as iconStar } from './⭐.png';
export { default as iconDarts } from './🎯.png';
export { default as iconStudent } from './🎓.png';
export { default as iconHome } from './🏠.png';
export { default as iconTree } from './🌳.png';
export { default as iconTriangle } from './📐.png';
export { default as iconVessilya } from './👰.png';
export { default as iconHeadphones } from './🎧.png';
export { default as iconLupa } from './🔍.png';
export { default as iconOffice } from './🏢.png';
export { default as iconTassel } from './🖌️.png';
export { default as iconCloud } from './☁️.png';
export { default as iconGamePad } from './🎮.png';
export { default as iconGlobus } from './🌐.png';
export { default as iconBulb } from './💡.png';
export { default as iconNotes } from './🎶.png';
export { default as iconBook } from './📖.png';
export { default as iconShine } from './✨.png';
export { default as iconPlenka } from './🎞️.png';
export { default as iconCircus } from './🎪.png';
export { default as iconBlockChain } from './🔗.png';
export { default as iconAI } from './🤖.png';
export { default as iconEmail } from './📧.png';
export { default as iconSiren } from './📢.png';
export { default as iconMicrophone } from './🎤.png';
export { default as iconNewspaper } from './📰.png';
export { default as iconPencil } from './✏️.png';
export { default as iconCamera } from './🎥.png';
export { default as iconComedyMask } from './🎭.png';
export { default as iconMusical } from './🎼.png';
export { default as iconPeizaj } from './🖼️.png';
export { default as iconChuvak } from './🗣️.png';
export { default as iconMobila } from './📱.png';
export { default as iconKolokolchik } from './🔔.png'
export { default as iconOleg } from './oleg.png';
export { default as iconBlocknote} from './📋.png';
export { default as iconChumodan} from './💼.png';
export { default as iconFolder } from './📁.png';
export { default as iconTime} from './⏰.png';
export { default as iconZvonilka } from './📞.png';
export { default as iconHeart } from './💛.png';
export { default as iconIrina } from './irina.png';
export { default as iconOlena } from './olena.png';
export { default as iconMaxim} from './Maxim.png';
export { default as iconDanilka} from './danilka.png';
export { default as iconAndrei} from './andreios.png';